title: "Pooja Jeswani"
author: ""
description: "Hi there, welcome to my blog page. As an aspiring marketing professional, I decided to set up this page in order to feature some of my best writing work in order to provide one with an idea of my skill set" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "poojajeswani16@mail.com"
twitter_username: "@PoojaJeswani16"
github_username: "poojajeswani"
linkedin_username: "Pooja Jeswani"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
